[INFO -- 2018-09-15 12:02:38]
Starting flip_value script
version: 1.1
[INFO -- 2018-09-15 12:02:38]
Initialization strings:
[INFO -- 2018-09-15 12:02:38]
(1) file /tmp/lreg/lreg
[INFO -- 2018-09-15 12:02:38]
(2) set args /tmp/lreg/randInput /tmp/lreg/output
[INFO -- 2018-09-15 12:02:38]
initSignal:0
[INFO -- 2018-09-15 12:02:38]
endSignal:2
[INFO -- 2018-09-15 12:02:38]
faultModel:2
[EXCEPTION -- 2018-09-15 12:02:39]
pythonException: Unable to exit loop in struct fields; Exiting wihtout making a bit flip
[INFO -- 2018-09-15 12:02:39]
Backtrace BEGIN:
#0  std::allocator<double>::~allocator (this=0x7fffffffd890, __in_chrg=<optimized out>) at /usr/include/c++/7/bits/allocator.h:139
#1  0x000055555555657a in std::_Vector_base<double, std::allocator<double> >::_Vector_impl::~_Vector_impl (this=0x7fffffffd890, __in_chrg=<optimized out>) at /usr/include/c++/7/bits/stl_vector.h:81
#2  0x00005555555565e7 in std::_Vector_base<double, std::allocator<double> >::~_Vector_base (this=0x7fffffffd890, __in_chrg=<optimized out>) at /usr/include/c++/7/bits/stl_vector.h:163
#3  0x000055555555602d in std::vector<double, std::allocator<double> >::~vector (this=0x7fffffffd890, __in_chrg=<optimized out>) at /usr/include/c++/7/bits/stl_vector.h:435
#4  0x0000555555555770 in train (iterations=30000, alpha=0.00020000000000000001, N=2, stopsWhenStable=true) at lreg.cpp:126
#5  0x0000555555555c26 in main (argc=3, argv=0x7fffffffde68) at lreg.cpp:182

134	      : __allocator_base<_Tp>(__a) { }
135	
136	      template<typename _Tp1>
137		allocator(const allocator<_Tp1>&) throw() { }
138	
139	      ~allocator() throw() { }
140	
141	      // Inherit everything else.
142	    };
143	

Backtrace END
Memory content before bitflip:0x030x000x000x00
Fault Model: Random bit-flip
base address to flip value: 0x7fffffffd92c
address max offset: 4
Memory content after  bitflip:0xdd0x280x210x2d
frame name: main
symbol name: testCases
symbol filename: lreg.cpp
symbol line: 164
value: 757147869
value address: 0x7fffffffd92c
Type: The type is an integer type.
Type sizeof: 4

[INFO -- 2018-09-15 12:02:39]
Fault Injection Successful after 1.4454762935638428s
