[INFO -- 2018-11-26 17:01:57]
Starting flip_value script
version: 1.1
[INFO -- 2018-11-26 17:01:57]
Initialization strings:
[INFO -- 2018-11-26 17:01:57]
(1) file /tmp/lreg/lreg
[INFO -- 2018-11-26 17:01:57]
(2) set args /tmp/lreg/randInput /tmp/lreg/output
[INFO -- 2018-11-26 17:01:57]
initSignal:0
[INFO -- 2018-11-26 17:01:57]
endSignal:3
[INFO -- 2018-11-26 17:01:57]
faultModel:2
[EXCEPTION -- 2018-11-26 17:01:59]
pythonException: empty range for randrange() (0,0, 0)
[EXCEPTION -- 2018-11-26 17:01:59]
gdbException: Cannot access memory at address 0xd166e41fe76bdee8
[INFO -- 2018-11-26 17:01:59]
Backtrace BEGIN:
#0  log1 (error=<synthetic pointer>, delta=<synthetic pointer>, x=5) at ../sysdeps/ieee754/dbl-64/e_pow.c:329
#1  __ieee754_pow_sse2 (x=5, y=3) at ../sysdeps/ieee754/dbl-64/e_pow.c:103
#2  0x00007ffff76bcb14 in __pow (x=5, y=3) at w_pow_compat.c:30
#3  0x0000555555556826 in std::pow<double, unsigned int> (__x=5, __y=3) at /usr/include/c++/7/cmath:418
#4  0x0000555555555814 in predict (v=5) at lreg.cpp:116
#5  0x0000555555555a53 in partialDerivate (pos1=1, pos2=1) at lreg.cpp:142
#6  0x0000555555555bbe in adjust (alpha1=2.2222199999999999e-05, alpha2=2.2222199999999999e-05) at lreg.cpp:156
#7  0x0000555555555ee0 in train (iter1=30000, iter2=30000, N=4, alpha1=2.2222199999999999e-05, alpha2=2.2222199999999999e-05, stopsWhenStable=true) at lreg.cpp:193
#8  0x0000555555556467 in main (argc=3, argv=0x7fffffffde58) at lreg.cpp:253

324	in ../sysdeps/ieee754/dbl-64/e_pow.c

Backtrace END
Memory content before bitflip:0x000x000x000x00
Fault Model: Random bit-flip
base address to flip value: 0x55555575b1b8 
address max offset: 4
Memory content after  bitflip:0x960x800xa30x87
frame name: std::pow<double, unsigned int>
symbol name: detected
symbol filename: lreg.cpp
symbol line: 58
value: -2019327850
value address: 0x55555575b1b8 <detected>
Type: The type is an integer type.
Type sizeof: 4

[INFO -- 2018-11-26 17:01:59]
Fault Injection Successful after 2.463264226913452s
[INFO -- 2018-11-26 17:01:59]
event type: exit
[EXCEPTION -- 2018-11-26 17:01:59]
exit code: no exit code available
